### ISSUE TITLE
Question about training custom dataset

### ISSUE THREAD

**Issue by Maeve-D** [xingyizhou/CenterTrack#103]
I want to train the model to track one object. 
My dataset has 2 part. 1.image folder :images. 2.train.json, which can be correctly uesd in CenterNet.

python main.py tracking --exp_id coco_tracking --dataset custom --custom_dataset_ann_path ../data/Cap2/train.json --custom_dataset_img_path ../data/Cap2/ --input_h 960 --input_w 1280 --num_classes 1 --pre_hm --ltrb_amodal --same_aug --hm_disturb 0.05 --lost_disturb 0.4 --fp_disturb 0.1 --gpus 0

1.KeyError: Caught KeyError in DataLoader worker process 0.
2./cls_id = int(self.cat_ids[ann['category_id']]) KeyError: 0

I set the num_workers in opt.py to 0. But still meet question 1.
And I have no idea how 
Thank you for your reply : D

**Comment by Maeve-D** [comment]
I find that if I input one image, it works. However, if input a image folder, it shows this problem.

**Comment by Maeve-D** [comment]
I find that if the number of images in the folder is less than 34, the training part works. However, if the number of images in the folder is large, it still has the problem

**Comment by Maeve-D** [comment]
I find that when I modify this value, and the number of training images it smaller than default value, it works. 
self.parser.add_argument('--batch_size', type=int, default=32,
                             help='batch size')

**Comment by Veronica1997** [comment]
thanks for your solution! when you train with your own dataset, are there any modify in the code?
