### ISSUE TITLE
Some questions about debug mode

### ISSUE THREAD

**Issue by xs020420** [xingyizhou/CenterTrack#104]
Hi! There is some question about debug mode.
In my case, I do not want to any interaction about X server. However,when I set debug to 0, It reports key error "_ret[generic]_" while running _demo.py_ . I'm just starting to use this code. Can you give me some advise to solve the problem?

**Comment by xs020420** [comment]
I have commited all _cv2.imshow_  code and run demo.py in debug 1.But I still not clear how to use debug 0 .

**Comment by xingyizhou** [comment]
Hi,
  Sorry for the confusion, `--debug 0` is not implemented properly in the code, as I didn't take care of `opt.debug > 0` and `opt.debug >= 0`. Please use `debug 1` if you just want to visualize the bounding boxes or `debug 2` if you want to visualize the heatmaps as well.

**Comment by xs020420** [comment]
Thx for reply! I got it!
