### ISSUE TITLE
KITTI full test ，ValueError: Ground truth not found. 

### ISSUE THREAD

**Issue by chenjinhua1993** [xingyizhou/CenterTrack#110]
First， in “CenterTrack/src/tools/eval_kitti_track/evaluate_tracking.py”， line 99
filename_test_mapping = "./tools/eval_kitti_track/data/tracking/" + \
          "evaluate_tracking{}.seqmap".format(split_version) , I got the first error, can not find the "evaluate_tracking**test**.seqmap" file ,because there not exist such a file , I change the code:

filename_test_mapping = "./tools/eval_kitti_track/data/tracking/" + \
          "evaluate_tracking.seqmap.{}".format(split_version)  then, it works.

however, I got the second one as following, I have tried some ways, but it did 't work. 
Processing Result for KITTI Tracking Benchmark
Loading Results - Success
Evaluate Object Class: CAR
extend f_data 148 148
extend f_data 115 115
extend f_data 216 216
extend f_data 716 716
extend f_data 166 166
extend f_data 350 350
extend f_data 153 153
extend f_data 181 181
extend f_data 405 405
extend f_data 935 905
extend f_data 174 174
extend f_data 674 674
Traceback (most recent call last):
  File "tools/eval_kitti_track/evaluate_tracking.py", line 983, in <module>
    success = evaluate(result_sha,mail,split_version=split_version)
  File "tools/eval_kitti_track/evaluate_tracking.py", line 932, in evaluate
    raise ValueError("Ground truth not found.")
ValueError: Ground truth not found.

**Comment by ggsggs** [comment]
Hello,

how did you solve the issue in the end? I am having, I think, a similar error.

I did not expect the "test" split of the KITTI dataset to try to launch evaluation, since there's an evaluation server for that and the ground truth of the test set is not public.

At least the predicted annotations are saved in `exp/tracking/<EXP_ID>/results_kitti_tracking`.

Find below the command I used and the error at the end. The tracking process ran to completion (see last img being processed below).

``` bash
python test.py tracking --exp_id k_test --dataset kitti_tracking --dataset_version test --pre_hm --track_thresh 0.4 --load_model ../models/kitti_half.pth
...
...
...
kitti_test |################################| [11094/11095]|Tot: 0:35:28 |ETA: 0:00:01 |tot 0.185s (0.191s) |load 0.000s (0.000s) |pre 0.004s (0.006s) |net 0.179s (0.179s) |dec 0.002s (0.005s) |post 0.000s (0.001s) |merge 0.000s (0.000s) |track 0.000s (0.000s) 
Processing Result for KITTI Tracking Benchmark
Traceback (most recent call last):
  File "tools/eval_kitti_track/evaluate_tracking.py", line 984, in <module>
    success = evaluate(result_sha,mail,split_version=split_version)
  File "tools/eval_kitti_track/evaluate_tracking.py", line 919, in evaluate
    t_sha=result_sha, mail=mail,cls=c,split_version=split_version)
  File "tools/eval_kitti_track/evaluate_tracking.py", line 103, in __init__
    with open(filename_test_mapping, "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: './tools/eval_kitti_track/data/tracking/evaluate_trackingtest.seqmap'
```

**Comment by chenjinhua1993** [comment]
sorry, I didn't solve this problem.

**Comment by lushbng** [comment]
Hello,
I have same question . but i donnot how to solve it

**Comment by dodeokwangyooo** [comment]
Hi！
Have u solved this problem？Can u tell me how to solve it？ thank u
