### ISSUE TITLE
When test, if it need to run detect first and then run the tracking?

### ISSUE THREAD

**Issue by ghoshaw** [xingyizhou/CenterTrack#114]
As the title, what is the pipeline of tracking ?
If it should run center detect and then run centertrack? or how to given the input image of t-1?
And the detection only runs one time?

**Comment by xingyizhou** [comment]
For each frame, we run detection (with tracking offset output), and then run id-association. Then the next frame. We have the image of `t-1` when we are running at `t`.

**Comment by ghoshaw** [comment]
ok, thanks!
