### ISSUE TITLE
Cannot detect anything after trainning MOT17dataset

### ISSUE THREAD

**Issue by Maeve-D** [xingyizhou/CenterTrack#122]
I use :
python main.py tracking --exp_id mot17_half --dataset mot --dataset_version 17halftrain --pre_hm --ltrb_amodal --same_aug --hm_disturb 0.05 --lost_disturb 0.4 --fp_disturb 0.1 --gpus 0,1 --load_model ../models/crowdhuman.pth

And here is the trainning process.
tracking/mot17_half |############################### | train: [70][330/333]|Tot: 0:06:21 |ETA: 0:00:04 |tot 0.8864 |hm 0.1909 |wh 0.5056 |reg 0.1414 |ltrb_amodal 0.4991 |tracking 0.4537 |Da
tracking/mot17_half |############################### | train: [70][331/333]|Tot: 0:06:23 |ETA: 0:00:03 |tot 0.8858 |hm 0.1908 |wh 0.5056 |reg 0.1413 |ltrb_amodal 0.4986 |tracking 0.4534 |Da
tracking/mot17_half |################################| train: [70][332/333]|Tot: 0:06:24 |ETA: 0:00:02 |tot 0.8863 |hm 0.1907 |wh 0.5058 |reg 0.1413 |ltrb_amodal 0.4994 |tracking 0.4538 |Data 0.032s(0.041s) |Net 1.154s

Then i got model_last.pth . And use find model_last.pth in CenterTrack-master\exp\tracking\mot17_half:
python demo.py tracking --load_model model_last.pth --dataset mot --demo detect_person.mp4
But detected nothing. Only video.

Can you tell me where the problem??

**Comment by xingyizhou** [comment]
Hi,
  Thank you for bringing this up. `demo.py` uses the coco model with 80 categories by default. To change to the 1 category MOT model, you need to add `--num_class 1` when running demo to make the parameters be loaded properly. The log should have printed out information about not loading some parameters. I will add this to the instruction.

**Comment by Maeve-D** [comment]
wow!!!
It works!Thank you~~:D

**Comment by lt573152873** [comment]
same_aug  ?  no parameters .  is same_aug_pre?
