### ISSUE TITLE
Tracker is broken after rebirth commit

### ISSUE THREAD

**Issue by qingswu** [xingyizhou/CenterTrack#126]
https://github.com/xingyizhou/CenterTrack/blob/ee6bc39ec68ce30cf816f6ae7f7ac83661ed3460/src/lib/utils/tracker.py#L125

Hi Xingyi,  in your recent commit regarding rebirth you delete `self.tracks=ret`, is this intended or by accident? The tracking code is broken because of missing this line. No old track is associated with new detections.

**Comment by xingyizhou** [comment]
Hi,
  Thanks for pointing out the issue. It is indeed a typo. I have fixed it in the most recent commit.

**Comment by qingswu** [comment]
Great!
