### ISSUE TITLE
 the performance while using static images and sequence datasets.

### ISSUE THREAD

**Issue by xiaqing10** [xingyizhou/CenterTrack#127]
nice work.
there are two questions:

1, when i trained my datasets using static images, the results was very good,  should i
 create sequence datasets just like mot17 to get better results. i don't know the performance between static images and mot17?

2, i  used centernet(res50, no dcn) and centertrack(res50 ,no dcn) to train common datasets, while centertnet get higher results(map:0.8) and centertrack only get 0.71 map in detection branch.
what should i do get same results?

**Comment by Veronica1997** [comment]
Have you try to use the pretrained model in centernet to train centertrack? I tried this way, and the map in centertrack can increase a lot.
And how you convert the static datasets to sequece datasets? I trained my own custom datasets(coco or voc format), I don't know how to evaluate the MOT metrics , can you help me? Thanks!

**Comment by xiaqing10** [comment]
yes, i use centernet pretrained model(map 0.8) to train centertrack, but the result get worse.
i think you do not convert static datasets to sequence datasets, you could label some data using mot17 method.
