### ISSUE TITLE
Still can't save video

### ISSUE THREAD

**Issue by starsky68** [xingyizhou/CenterTrack#131]
I used --save_video = ‘../results’ and video_h and video_w still cannot get the result of saving the video after running the demo.

frame 36 |tot 0.055s |load 0.000s |pre 0.017s |net 0.031s |dec 0.002s |post 0.004s |merge 0.000s |display 0.009s |
go
frame 37 |tot 0.055s |load 0.000s |pre 0.017s |net 0.030s |dec 0.002s |post 0.005s |merge 0.000s |display 0.010s |
go
frame 38 |tot 0.054s |load 0.000s |pre 0.017s |net 0.031s |dec 0.002s |post 0.004s |merge 0.000s |display 0.009s |
go
frame 39 |tot 0.054s |load 0.000s |pre 0.017s |net 0.031s |dec 0.002s |post 0.004s |merge 0.000s |display 0.010s |
go
frame 40 |tot 0.055s |load 0.000s |pre 0.017s |net 0.031s |dec 0.002s |post 0.004s |merge 0.000s |display 0.010s |

**Comment by christopherkettell** [comment]
@starsky68  did you manage to resolve this? Currently stuck on this myself.
Any feedback or guidance would be welcome - thank you in advance :)

**Comment by ifanshida** [comment]
> 

Hello!
At present, I have encountered that the saved file is only 1K in size and cannot be played. The player prompt cannot be decoded.
Do you know why? I hope you can help me. Thank you very much
