### ISSUE TITLE
Question: Output parameters

### ISSUE THREAD

**Issue by agirbau** [xingyizhou/CenterTrack#137]
Hello!

First of all, thank you for posting the code, it's a very nice work!

I'm trying to understand the outputs of the network. As far as I understand:

'hm': heatmap of the centers.
'reg': regression from center in image 't-1' to the center in time 't' (?)
'wh': width and height estimation from the centers
'tracking': (?)
'ltrb_amodal': (?)
'pre_inds': indices of the centers in image 't-1'. 

Could you please explain these parameters? Thank you for your time and work!

**Comment by agirbau** [comment]
For anyone else that asks the same question:
'reg' corresponds to a "refinement" of the centers.
'tracking' corresponds to the relation between centers in 't' to centers in 't-1', in order to relate detections from 't-1' to 't'.

Closing this issue, as it was basically for this question!

**Comment by LingyvKong** [comment]
> hello, do you know the meaning of 'ltrb_amodal' ?

I guess it's "left-top-right-bottom" for predicting the box size, as mentioned in [#115](https://github.com/xingyizhou/CenterTrack/issues/115)
