### ISSUE TITLE
could not connect to display

### ISSUE THREAD

**Issue by xueyaqing** [xingyizhou/CenterTrack#141]
Is there anyone meet this question, I use docker ubuntu18.04,pytorch 1.4,cuda 10.0
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/xueyq/anaconda3/envs/centertrack/lib/python3.6/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by upxinxin** [comment]
Sorry to disturb you. But I met the same question, could you tell me how to solve it? Thanks a lot!

**Comment by xueyaqing** [comment]
The reason of this issue is that my service has no&nbsp;Graphical interface, so I commented all of the "cv2.imgshow()" code blocks in the whole program.You can try this, or you can download the package of Graphical interface to use the cv2.imgshow() to show the visual results.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xingyizhou/CenterTrack"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月5日(星期四) 下午2:40
收件人:&nbsp;"xingyizhou/CenterTrack"<CenterTrack@noreply.github.com&gt;;
抄送:&nbsp;"阿亚亚亚"<1446005161@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [xingyizhou/CenterTrack] could not connect to display (#141)





 
Sorry to disturb you. But I met the same question, could you tell me how to solve it? Thanks a lot!
