### ISSUE TITLE
train my own 3d data loss  meet trouble

### ISSUE THREAD

**Issue by lyxbyr** [xingyizhou/CenterTrack#147]
thanks for your work
i convert my data to coco format like kitti,but train loss 
hm 3.5110 |wh 0.0000 |reg 0.0000 |dep 0.0000 |dim 0.0000 |rot 1.3863 |amodel_offset 0.0000 
only hm is decrease,wh,reg,dep,dim,amodel_offset always 0, rot always 1.3863,but check my data format is right like kitt convert to coco format 

after train two epochs ,loss is hm 2.3234 |wh 0.0203 |reg 0.0002 |dep 0.0140 |dim 0.0009 |rot 1.3868 |,wh,reg,dep,dim loss very low, i don not know it is normal

**Comment by DonaldKam** [comment]
I met the same issue, how did you deel with the problem？

**Comment by youonlytrackonce** [comment]
Hello,

did you solve the problem?

**Comment by DonaldKam** [comment]
Thank you and I'll reply to your e-mail ASAP.Best regards!
                                              HM.G/Donald Kam
