### ISSUE TITLE
The result of car tracking

### ISSUE THREAD

**Issue by board-man** [xingyizhou/CenterTrack#148]
I have tried to use CentrerTrack for car tracking with the pretrained model - kitti_half.pth. And I used the order as below:

 python demo.py tracking --load_model ../models/kitti_half.pth --num_class 3  --demo ../videos/nuscenes_mini.mp4   

Why the bounding box in the result was label as bicycle? And when I change the arguments --num_class  to 2 , it even could not track anything.

**Comment by xingyizhou** [comment]
Hi, by default, the demo script uses the nuscenes name order. You can try adding `--dataset kitti_tracking` when using kitti pretrained models.

**Comment by board-man** [comment]
Got it. Thanks a lot!
