### ISSUE TITLE
train own 3d data when test predict depth is  too large(3d box visualization is small in the object)?

### ISSUE THREAD

**Issue by lyxbyr** [xingyizhou/CenterTrack#149]
thanks for your works! i use own camera intrinsic parameter,convert my 3d data to coco format like kitti format(checked it, them are the same format), but the 3d box is small when  tested , i confirm  use the same camera intrinsic parameter when training and testing ,then multiply the predicted depth by 0.4, it seems that the 3D box is more normal. Could you tell me what's wrong?
my picture resolution 1920*1020 , code set  default_resolution = [1024, 1920]
  Looking forward to  your  reply. @xingyizhou

**Comment by anstadnik** [comment]
Hi, @lyxbyr. I see that you've closed the issue, does it mean that you have fixed the problem? If so, what was the problem?

**Comment by anstadnik** [comment]
If somebody will stumble into that in future, most probably `keep_rez` option in demo.py is what you're looking for.
