### ISSUE TITLE
About kitti_half and kitti_half_sc

### ISSUE THREAD

**Issue by yustaub** [xingyizhou/CenterTrack#155]
Hi, xingyizhou. There are some question I want to ask.
1. **kitti_half** is also `use the first half frames for training and the second for validation`, if there is odd number in a sequence, how to split it?
2. what is the meaning of **kitti_half_sc** , I can not find the definition of this.
Very appreciate for your reoly!!

**Comment by xingyizhou** [comment]
Thank you for your interests.
1. The code for the split is [here](https://github.com/xingyizhou/CenterTrack/blob/master/src/tools/convert_kittitrack_to_coco.py#L93). We use [0, L//2) for training and [L//2, L) for validation.
2. It means train from "scratch". Actually it uses ImageNet pretrain. It is in contrast to using nuScenes pretrain.

**Comment by yustaub** [comment]
thanks for your reply! @xingyizhou

**Comment by yustaub** [comment]
Sorry to bother u again, sir. Will it support kitti 3D tracking later?
