### ISSUE TITLE
can't open file 'tools/nuscenes-devkit/python-sdk-alpha02/nuscenes/eval/tracking/evaluate.py'

### ISSUE THREAD

**Issue by yustaub** [xingyizhou/CenterTrack#158]
Hi, xingyizhou. I download nuscenes dataset and produce the json file and run `python test.py tracking,ddd --exp_id nuScenes_3Dtracking --load_model ../models/nuScenes_3Dtracking.pth --dataset nuscenes --track_thresh 0.1 --pre_hm`, then error happened, **python-sdk** I can find it in [https://github.com/nutonomy/nuscenes-devkit](url) but I can not find **python-sdk-alpha02**, very appreciate for your reply!!
nuScenes_3Dtracking |############################### | [36110/36114]|Tot: 1:18:21 |ETA: 0:00:01 |tot 0.051s (0.074s) |load 0.000s (0.000s) |pre 0.005s (0.007s) |net 0.037s (0.050s) |dec 0.004s (0.007s) |post 0.005s (0.008s) |merge 0.000s (0nuScenes_3Dtracking |############################### | [36111/36114]|Tot: 1:18:21 |ETA: 0:00:01 |tot 0.084s (0.074s) |load 0.000s (0.000s) |pre 0.012s (0.007s) |net 0.062s (0.050s) |dec 0.004s (0.007s) |post 0.005s (0.008s) |merge 0.000s (0nuScenes_3Dtracking |############################### | [36112/36114]|Tot: 1:18:21 |ETA: 0:00:01 |tot 0.054s (0.074s) |load 0.000s (0.000s) |pre 0.006s (0.007s) |net 0.037s (0.050s) |dec 0.004s (0.007s) |post 0.005s (0.008s) |merge 0.000s (0nuScenes_3Dtracking |################################| [36113/36114]|Tot: 1:18:21 |ETA: 0:00:01 |tot 0.054s (0.074s) |load 0.000s (0.000s) |pre 0.006s (0.007s) |net 0.038s (0.050s) |dec 0.004s (0.007s) |post 0.005s (0.008s) |merge 0.000s (0.000s) |track 0.001s (0.001s) 
Converting nuscenes format...
python: can't open file 'tools/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/evaluate.py': [Errno 2] No such file or directory
python: can't open file 'tools/nuscenes-devkit/python-sdk-alpha02/nuscenes/eval/tracking/evaluate.py': [Errno 2] No such file or directory

**Comment by yustaub** [comment]
I remove the line `os.system('python ' + \
        'tools/nuscenes-devkit/python-sdk-alpha02/nuscenes/eval/tracking/evaluate.py ' +\
        '{}/results_nuscenes_{}.json '.format(save_dir, task) + \
        '--output_dir {}/nuscenes_evaltracl__output/ '.format(save_dir) + \
        '--dataroot ../data/nuscenes/v1.0-trainval/')` and get the result:
### Final results ###

```
Per-class results:
		AMOTA	AMOTP	RECALL	MOTAR	GT	MOTA	MOTP	MT	ML	FAF	TP	FP	FN	IDS	FRAG	TID	LGD
bicycle 	0.000	1.758	0.324	0.000	1993	0.000	0.814	11	72	90.9	521	1659	1347	125	56	1.65	2.67
bus     	0.116	1.450	0.152	0.828	2112	0.125	0.708	7	91	3.6	319	55	1790	3	12	3.30	5.22
car     	0.261	1.109	0.342	0.528	58317	0.163	0.567	450	2253	147.0	17978	8478	38352	1987	1230	1.82	3.27
motorcy 	0.010	1.669	0.241	0.097	1977	0.020	0.790	4	82	26.8	413	373	1500	64	56	2.58	4.07
pedestr 	0.059	1.495	0.210	0.338	25423	0.062	0.789	42	1179	70.8	4681	3101	20091	651	619	2.43	4.38
trailer 	0.000	1.871	0.239	0.000	2425	0.000	1.133	4	77	137.7	465	1611	1845	115	102	2.53	4.27
truck   	0.030	1.449	0.104	0.537	9650	0.055	0.679	20	477	12.6	985	456	8648	17	26	1.98	4.81

Aggregated results:
AMOTA	0.068
AMOTP	1.543
RECALL	0.230
MOTAR	0.332
GT	14556
MOTA	0.061
MOTP	0.783
MT	538
ML	4231
FAF	69.9
TP	25362
FP	15733
FN	73573
IDS	2962
FRAG	2101
TID	2.33
LGD	4.10
Eval time: 2229.9s
```
I want to know why there is MOTP >1, the upper bound of MOTP is 1.
Very appreciate for your reply!! @xingyizhou

**Comment by zrx0311** [comment]
Hello, I encountered such a problem when I was creating json file. Do you know what went wrong？

Loading NuScenes tables for version v1.0-trainval...
Traceback (most recent call last):
  File "convert_nuScenes.py", line 369, in <module>
    main()
  File "convert_nuScenes.py", line 73, in main
    version=SPLITS[split], dataroot=data_path, verbose=True)
  File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/nuscenes/nuscenes.py", line 81, in __init__
    map_record['mask'] = MapMask(osp.join(self.dataroot, map_record['filename']), resolution=map_resolution)
  File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/nuscenes/utils/map_mask.py", line 23, in __init__
    assert osp.exists(img_file), 'map mask {} does not exist'.format(img_file)
AssertionError: map mask ../../data/nuscenes/v1.0-trainval/maps/53992ee3023e5494b90c316c183be829.png does not exist

**Comment by yustaub** [comment]
you may miss pic in folder "map" @zrx0311

**Comment by zrx0311** [comment]
Isn't there only five JSON files in maps？@yustaub

**Comment by yustaub** [comment]
four '*.png' picture in folder "maps" @zrx0311

**Comment by zrx0311** [comment]
The Map Expansion Pack (V1.2) I downloaded from the official site contained only five JSON files...

**Comment by zrx0311** [comment]
The Map Expansion Pack (V1.2) I downloaded from the official site contained only five JSON files...@yustaub

**Comment by yustaub** [comment]
maybe there are some mistakes when you download nuscenes dataset @zrx0311

**Comment by zrx0311** [comment]
I'll check it again. Thank you very much！@yustaub

**Comment by zrx0311** [comment]
When I was running the test file, I encountered such a problem that I thought my data set might not be set properly, but I couldn't find the problem. Have you ever come across such a situation?

Dataset version 
==> initializing val data from /media/nuaadip/768C60BB8C60780F/ZRX/CenterTrack/src/lib/../../data/nuscenes/annotations/val.json, 
 images from /media/nuaadip/768C60BB8C60780F/ZRX/CenterTrack/src/lib/../../data/nuscenes/v1.0-trainval ...
loading annotations into memory...
Done (t=5.61s)
creating index...
index created!
Creating video index!
Loaded val 36114 samples
Creating model...
Using node type: (<class 'model.networks.dla.DeformConv'>, <class 'model.networks.dla.DeformConv'>)
Warning: No ImageNet pretrain!!
loaded ../models/nuScenes_3Dtracking.pth, epoch 70
nuScenes_3DtrackingTraceback (most recent call last):
  File "test.py", line 195, in <module>
    prefetch_test(opt)
  File "test.py", line 87, in prefetch_test
    for ind, (img_id, pre_processed_images) in enumerate(data_loader):
  File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "test.py", line 43, in __getitem__
    image, scale, input_meta)
  File "/media/nuaadip/768C60BB8C60780F/ZRX/CenterTrack/src/lib/detector.py", line 213, in pre_process
    self._transform_scale(image)
  File "/media/nuaadip/768C60BB8C60780F/ZRX/CenterTrack/src/lib/detector.py", line 181, in _transform_scale
    height, width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by zrx0311** [comment]
When I was running the test file, I encountered such a problem that I thought my data set might not be set properly, but I couldn't find the problem. Have you ever come across such a situation?@yustaub

Dataset version
==> initializing val data from /media/nuaadip/768C60BB8C60780F/ZRX/CenterTrack/src/lib/../../data/nuscenes/annotations/val.json,
images from /media/nuaadip/768C60BB8C60780F/ZRX/CenterTrack/src/lib/../../data/nuscenes/v1.0-trainval ...
loading annotations into memory...
Done (t=5.61s)
creating index...
index created!
Creating video index!
Loaded val 36114 samples
Creating model...
Using node type: (<class 'model.networks.dla.DeformConv'>, <class 'model.networks.dla.DeformConv'>)
Warning: No ImageNet pretrain!!
loaded ../models/nuScenes_3Dtracking.pth, epoch 70
nuScenes_3DtrackingTraceback (most recent call last):
File "test.py", line 195, in
prefetch_test(opt)
File "test.py", line 87, in prefetch_test
for ind, (img_id, pre_processed_images) in enumerate(data_loader):
File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in next
return self._process_data(data)
File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
data.reraise()
File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
data = fetcher.fetch(index)
File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/nuaadip/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "test.py", line 43, in getitem
image, scale, input_meta)
File "/media/nuaadip/768C60BB8C60780F/ZRX/CenterTrack/src/lib/detector.py", line 213, in pre_process
self._transform_scale(image)
File "/media/nuaadip/768C60BB8C60780F/ZRX/CenterTrack/src/lib/detector.py", line 181, in _transform_scale
height, width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by zrx0311** [comment]
According to the data.md file, I cannot generate the JSON file and must organize the DATA set as follows：
  ~~~
  ${CenterTrack_ROOT}
  |-- data
  `-- |-- nuscenes
      `-- |-- v1.0-trainval
          |   |-- samples
          |   |   |-- CAM_BACK
          |   |   |   | -- xxx.jpg
          |   |   |-- CAM_BACK_LEFT
          |   |   |-- CAM_BACK_RIGHT
          |   |   |-- CAM_FRONT
          |   |   |-- CAM_FRONT_LEFT
          |   |   |-- CAM_FRONT_RIGHT
          |-- |-- maps
          |-- |-- v1.0-trainval
          |-- v1.0-test
              |-- maps
              |v1.0-test 

Do you do the same？
thanks！

**Comment by yustaub** [comment]
maybe some error happend in your download file, I download the nuscenes and can get the json file successfully, you can check it

**Comment by ifanshida** [comment]
> According to the data.md file, I cannot generate the JSON file and must organize the DATA set as follows：
> 
> ```
> ${CenterTrack_ROOT}
> |-- data
> `-- |-- nuscenes
>     `-- |-- v1.0-trainval
>         |   |-- samples
>         |   |   |-- CAM_BACK
>         |   |   |   | -- xxx.jpg
>         |   |   |-- CAM_BACK_LEFT
>         |   |   |-- CAM_BACK_RIGHT
>         |   |   |-- CAM_FRONT
>         |   |   |-- CAM_FRONT_LEFT
>         |   |   |-- CAM_FRONT_RIGHT
>         |-- |-- maps
>         |-- |-- v1.0-trainval
>         |-- v1.0-test
>             |-- maps
>             |v1.0-test 
> 
> Do you do the same？
> thanks！
> ```

Like you, I have encountered the same problem of data set conversion format. But my mistakes are as follows:


(torch) E:\Desktop\CenterTrack-master\src\tools>python convert_nuScenes.py
======
Loading NuScenes tables for version v1.0-trainval...
Traceback (most recent call last):
  File "convert_nuScenes.py", line 369, in <module>
    main()
  File "convert_nuScenes.py", line 73, in main
    version=SPLITS[split], dataroot=data_path, verbose=True)
  File "D:\Anaconda3\envs\torch\lib\site-packages\nuscenes\nuscenes.py", line 69, in __init__
    self.category = self.__load_table__('category')
  File "D:\Anaconda3\envs\torch\lib\site-packages\nuscenes\nuscenes.py", line 136, in __load_table__
    with open(osp.join(self.table_root, '{}.json'.format(table_name))) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../data/nuscenes/v1.0-trainval/v1.0-trainval\\category.json

I repositioned the folder according to your directory, but it still doesn't work correctly. Do you know what the problem is?

**Comment by ifanshida** [comment]
> According to the data.md file, I cannot generate the JSON file and must organize the DATA set as follows：
> 
> ```
> ${CenterTrack_ROOT}
> |-- data
> `-- |-- nuscenes
>     `-- |-- v1.0-trainval
>         |   |-- samples
>         |   |   |-- CAM_BACK
>         |   |   |   | -- xxx.jpg
>         |   |   |-- CAM_BACK_LEFT
>         |   |   |-- CAM_BACK_RIGHT
>         |   |   |-- CAM_FRONT
>         |   |   |-- CAM_FRONT_LEFT
>         |   |   |-- CAM_FRONT_RIGHT
>         |-- |-- maps
>         |-- |-- v1.0-trainval
>         |-- v1.0-test
>             |-- maps
>             |v1.0-test 
> 
> Do you do the same？
> thanks！
> ```

Like you, I have encountered the same problem of data set conversion format. But my mistakes are as follows:


(torch) E:\Desktop\CenterTrack-master\src\tools>python convert_nuScenes.py
======
Loading NuScenes tables for version v1.0-trainval...
Traceback (most recent call last):
  File "convert_nuScenes.py", line 369, in <module>
    main()
  File "convert_nuScenes.py", line 73, in main
    version=SPLITS[split], dataroot=data_path, verbose=True)
  File "D:\Anaconda3\envs\torch\lib\site-packages\nuscenes\nuscenes.py", line 69, in __init__
    self.category = self.__load_table__('category')
  File "D:\Anaconda3\envs\torch\lib\site-packages\nuscenes\nuscenes.py", line 136, in __load_table__
    with open(osp.join(self.table_root, '{}.json'.format(table_name))) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../data/nuscenes/v1.0-trainval/v1.0-trainval\\category.json

I repositioned the folder according to your directory, but it still doesn't work correctly. Do you know what the problem is?
