### ISSUE TITLE
fatal error: cublas_v2.h

### ISSUE THREAD

**Issue by arthuremir** [xingyizhou/CenterTrack#16]
I'm building DCNv2.
While executing ./make.sh this error occured:

In file included from /usr/local/cuda/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
In file included from /home/user/carla_sdc/CenterTrack/src/lib/model/networks/DCNv2/src/cuda/dcn_v2_im2col_cuda.cu:7:
/home/user/anaconda3/envs/envi/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:7:10: fatal error: cublas_v2.h: No such file or directory
    7 | #include <cublas_v2.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

How do I solve it? What may be the reason? Googling didn't help. Thank you in advance!

I'm running on 
Ubuntu 19.10
CUDA 10.1
torch==1.4.0

**Comment by xingyizhou** [comment]
It's likely a gcc version issue. GCC 5.4/ 7.5 is tested. Can you try these versions?

**Comment by xingyizhou** [comment]
Closing this for now. Feel free to reopen if you still have questions.

**Comment by sisrfeng** [comment]
> Ubuntu 19.10
> CUDA 10.1
> torch==1.4.0

How  to install pytorch 1.4? I can only find 1.5 and <1.2 on official site.

**Comment by Muhtasham** [comment]
> How to install pytorch 1.4? I can only find 1.5 and <1.2 on official site.
pip install torch==1.4.0

**Comment by sisrfeng** [comment]
> > How to install pytorch 1.4? I can only find 1.5 and <1.2 on official site.
> > pip install torch==1.4.0

For pytorch 1.2:
# CUDA 10.0
pip install torch===1.2.0 torchvision===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html

# CUDA 9.2
pip install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html

If I use pip install torch==1.4.0,
will the proper torchvision be installed?

**Comment by naveenss1995** [comment]
Hi I am getting same error . Ubuntu 18.04 , torch 1.4.0, cuda 10.1

**Comment by Frank-Dz** [comment]
See answer here:

https://stackoverflow.com/a/66044636/12838403

Here I put the final solution:
- Step1: Run find 

```
find /usr/local/ -name cublas_v2.h
```
And we find the path of the file: 

/usr/local/cuda-10.2/targets/x86_64-linux/include/cublas_v2.h

- Step2: export the path
```
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/cuda-10.2/targets/x86_64-linux/include/
```

OK! Problem solved.

```export``` command can only work once. To make it a permanent change, you need to modify the ~/.bashrc:
```
vi ~/.bashrc
```
Add
```
CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/cuda-10.2/targets/x86_64-linux/include/
```
