### ISSUE TITLE
some difference of nuscenes tracking result

### ISSUE THREAD

**Issue by yustaub** [xingyizhou/CenterTrack#161]
Hi, xingyizhou. I have trained the centertrack on nuscenes for a week to get the tracking result, here is my result:
                trained(left) provided_model(right) 
AMOTA	0.068          0.068
AMOTP	1.561          1.543
RECALL	0.214          0.230
MOTAR	0.298           0.332
GT	        14556          14556
MOTA	0.056           0.061
MOTP	0.795           0.783
MT	        382              583
ML	       4739            4231
FAF	        57.4             69.9
TP	      20493            25362
FP	       11710            15733
FN	        79142            73573
IDS	         2262             2962
FRAG	1690              2101
TID	         2.20               2.33
LGD	         4.42               4.10

because my gpu is 12G, so I change the batch_size to 32 and lr_rate to 1.25e-4, there are 2 questions I want to ask:
1. there are some difference between my trained model **model_last.pth** and your provided model **nuScenes_3Dtracking.pth** such as AMOTP, RECALL ..., does this matter?
2. why the AMOTP is larger than 1? the upper bound of it is 1
thanks for your reply!!

**Comment by tianweiy** [comment]
AMOTP is the smaller the better. The upper bound is not 1. The performance seems similar between your trained one and provided for the most import AMOTA metrics

**Comment by yustaub** [comment]
but in the paper [https://arxiv.org/pdf/1907.03961.pdf](url), it shows that AMOTP is the bigger the better, in [https://www.nuscenes.org/tracking?externalData=all&mapData=all&modalities=Any](url) the AMOTP is the smaller the better, it confused me. Can you give some advice? @tianweiy

**Comment by tianweiy** [comment]
The lower the better. It is a measure of the localization error. I would follow the nusc definition for the dataset.

**Comment by yustaub** [comment]
got it. Thanks for your reply!

**Comment by javalier** [comment]
how can i get these message(AMOTP MOTA MOTP)?Do you use the CenterTrack -master's program?
