### ISSUE TITLE
mot17_fulltrain_sc are trained from ImageNet initialization, but why load crowdhuman.pth here?

### ISSUE THREAD

**Issue by acdart** [xingyizhou/CenterTrack#17]
https://github.com/xingyizhou/CenterTrack/blob/8c5ab8df6c2b6074a8694bd5d44138607a06fa93/experiments/mot17_fulltrain_sc.sh#L3

**Comment by xingyizhou** [comment]
Sorry this is a typo when preparing the training scripts. I have fixed it. Thank you for reporting this.

**Comment by acdart** [comment]
https://github.com/xingyizhou/CenterTrack/blob/eabc2f0905b608b86504276be4c5b72e6001cccc/experiments/mot17_fulltrain_sc.sh#L5

another question, you set '--resume', but changed the exp_id, so it may not find the model at current exp_id folder

**Comment by acdart** [comment]
also, when I run your code, it can't find trainval.json, as you set '--dataset_version 17trainval', but follow your data.md there is no trainval.json in annotations folder

**Comment by xingyizhou** [comment]
Thank you for point out the typos. They should be fixed now. I understand the current setup for different versions of MOT is redundant. It has been simplified in the most recent commit.
