### ISSUE TITLE
idx = pd.MultiIndex() TypeError: __new__() got an unexpected keyword argumen

### ISSUE THREAD

**Issue by lushbng** [xingyizhou/CenterTrack#175]
This error occurs when I run the "python test.py tracking --exp_id mot17_half --dataset mot --dataset_version 17halfval --pre_hm --ltrb_amodal --track_thresh 0.4 --pre_thresh 0.5 --resume" command

**Comment by lushbng** [comment]
File "tools/eval_motchallenge.py", line 98, in <module>
    metrics=metrics, generate_overall=True)
  File "/home/usr/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/motmetrics/metrics.py", line 188, in compute_many
    dfs += [MOTAccumulator.merge_event_dataframes(dfs)]
  File "/home/usr/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/motmetrics/mot.py", line 316, in merge_event_dataframes
    r = MOTAccumulator.new_event_dataframe()
  File "/home/usr/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/motmetrics/mot.py", line 243, in new_event_dataframe
    idx = pd.MultiIndex(levels=[[],[]], labels=[[],[]], names=['FrameId','Event'])
TypeError: __new__() got an unexpected keyword argument 'labels

**Comment by Keiku** [comment]
This is a problem with the version of pandas used by py-motmetrics. If you do the following, it will work fine.

```
pip install pandas==0.25.3
```

**Comment by lushbng** [comment]
Thank you for solving this problem



At 2020-12-22 11:07:42, "Keiichi Kuroyanagi" <notifications@github.com> wrote:

This is a problem with the version of pandas used by py-motmetrics. If you do the following, it will work fine.

pip install pandas==0.25.3

**Comment by Keiku** [comment]
@lushbng If it is resolved, please close it.

**Comment by ehsan1358** [comment]
'labels' keyword should be changed to 'codes'

**Comment by lushbng** [comment]
Hello
Do you know how to generate 42 video tracking results, I need to upload these 42 results to mot challenge.
Now run python test.py tracking --exp_id mot17_fulltrain --dataset mot --dataset_version 17test --pre_hm --ltrb_amodal --track_thresh 0.4 --pre_thresh 0.5 --resume
Only 21 video tracking results are saved, but 42 are needed for mot challenge



At 2021-04-29 19:17:52, "ehsan1358" ***@***.***> wrote:

'labels' keyword should be changed to 'codes'

**Comment by W-cxin** [comment]
> Hello Do you know how to generate 42 video tracking results, I need to upload these 42 results to mot challenge. Now run python test.py tracking --exp_id mot17_fulltrain --dataset mot --dataset_version 17test --pre_hm --ltrb_amodal --track_thresh 0.4 --pre_thresh 0.5 --resume Only 21 video tracking results are saved, but 42 are needed for mot challenge At 2021-04-29 19:17:52, "ehsan1358" ***@***.***> wrote: 'labels' keyword should be changed to 'codes' — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

hello,  I also met the same problem, have you solved yet? I'd appreciate it if you could tell me about it! Thanks a lot!
