### ISSUE TITLE
Which is the offset in Fig. 2 of the paper, the local offset of CenterNet or the offset of the displacement of tracking?

### ISSUE THREAD

**Issue by Keiku** [xingyizhou/CenterTrack#182]
As for my consideration, Fig. 2 of the paper shows the offset diagram of the tracking displacement, but the local offset diagram of CenterNet is omitted. Is this correct?

The paper says:

> CenterNet further regresses to a refined center local location using an analogous L1
loss L loc. The overall loss of CenterNet is a weighted sum of all three loss terms: focal
loss, size, and local location regression.

<img src="https://user-images.githubusercontent.com/199433/103638865-d73e4780-4f90-11eb-9c64-556e69edfa38.png" width="600px">

**Comment by xingyizhou** [comment]
You are correct, there is an additional local offset head. We omitted it in the figure for simplicity,

**Comment by Keiku** [comment]
Thank you for your answer.
