### ISSUE TITLE
How to run demo.py in pycharm

### ISSUE THREAD

**Issue by xiaoweidao** [xingyizhou/CenterTrack#208]
I am a python novice, sorry to disturb everyone, as the question shows, how to run the following program in pycharm, I can only run successfully in cmd`python demo.py tracking,ddd --load_model ../models/nuScenes_3Dtracking.pth --dataset nuscenes --pre_hm --track_thresh 0.1 --demo ../videos/nuscenes_mini.mp4 --test_focal_length 633`

**Comment by Wolfgang723** [comment]
modify opts.py argparse~

**Comment by xiaoweidao** [comment]
> modify opts.py argparse~


Thank you very much, your answer helped me a lot

**Comment by Wolfgang723** [comment]
> > modify opts.py argparse~
> > The demo.py tracking,ddd in demo.py tracking,ddd --load_model ../models/nuScenes_3Dtracking.pth --dataset nuscenes --pre_hm --track_thresh 0.1 --demo ../videos/nuscenes_mini.mp4 --test_focal_length 633 I don't know where to modify opts.py.
> > Can you help me? thank you very much

You should learn package argparse first。
As for command like --load_model ../models/nuScenes_3Dtracking.pth，modify the parameter 'default'   in self.parser.add_argument('--load_model', default='',help='path to pretrained model') (line 33 in opts.py):
 default="../models/nuScenes_3Dtracking.pth" 

As for command like --pre_hm  ,  modify the  parameter  'action'  in  self.parser.add_argument('--pre_hm', action='store_true')(line 207 in opts.py) : action = 'store_false'

As for command tacking,ddd , modify the  parameter  'default'  in    self.parser.add_argument('task', default='',
help='ctdet | ddd | multi_pose| tracking or combined with ,')(line 13 in opts.py) : default = "tacking,ddd"

我也是个新手，可以互相交流~

**Comment by xiaoweidao** [comment]
> As for command tacking,ddd , modify the parameter 'default' in self.parser.add_argument('

谢谢！我对 argparse有一定的了解，我之前就是像你讲的这样更改，还是没能运行出来，怎么设置运行都是demo.py: error: the following arguments are required: task，真让人头秃！

**Comment by xiaoweidao** [comment]
> > > modify opts.py argparse~
> > > The demo.py tracking,ddd in demo.py tracking,ddd --load_model ../models/nuScenes_3Dtracking.pth --dataset nuscenes --pre_hm --track_thresh 0.1 --demo ../videos/nuscenes_mini.mp4 --test_focal_length 633 I don't know where to modify opts.py.
> > > Can you help me? thank you very much
> 
> You should learn package argparse first。
> As for command like --load_model ../models/nuScenes_3Dtracking.pth，modify the parameter 'default' in self.parser.add_argument('--load_model', default='',help='path to pretrained model') (line 33 in opts.py):
> default="../models/nuScenes_3Dtracking.pth"
> 
> As for command like --pre_hm , modify the parameter 'action' in self.parser.add_argument('--pre_hm', action='store_true')(line 207 in opts.py) : action = 'store_false'
> 
> As for command tacking,ddd , modify the parameter 'default' in self.parser.add_argument('task', default='',
> help='ctdet | ddd | multi_pose| tracking or combined with ,')(line 13 in opts.py) : default = "tacking,ddd"
> 
> 我也是个新手，可以互相交流~

    self.parser.add_argument('--task',action='store_false', default='tracking,ddd',
                             help='ctdet | ddd | multi_pose '
                             '| tracking or combined with ,')（line 13 in opts.py）I changed this line of code, so it can run successfully. Thank you for your help！
谢谢你

**Comment by Wolfgang723** [comment]
> > > > modify opts.py argparse~
> > > > The demo.py tracking,ddd in demo.py tracking,ddd --load_model ../models/nuScenes_3Dtracking.pth --dataset nuscenes --pre_hm --track_thresh 0.1 --demo ../videos/nuscenes_mini.mp4 --test_focal_length 633 I don't know where to modify opts.py.
> > > > Can you help me? thank you very much
> > 
> > 
> > You should learn package argparse first。
> > As for command like --load_model ../models/nuScenes_3Dtracking.pth，modify the parameter 'default' in self.parser.add_argument('--load_model', default='',help='path to pretrained model') (line 33 in opts.py):
> > default="../models/nuScenes_3Dtracking.pth"
> > As for command like --pre_hm , modify the parameter 'action' in self.parser.add_argument('--pre_hm', action='store_true')(line 207 in opts.py) : action = 'store_false'
> > As for command tacking,ddd , modify the parameter 'default' in self.parser.add_argument('task', default='',
> > help='ctdet | ddd | multi_pose| tracking or combined with ,')(line 13 in opts.py) : default = "tacking,ddd"
> > 我也是个新手，可以互相交流~
> 
> ```
> self.parser.add_argument('--task',action='store_false', default='tracking,ddd',
>                          help='ctdet | ddd | multi_pose '
>                          '| tracking or combined with ,')（line 13 in opts.py）I changed this line of code, so it can run successfully. Thank you for your help！
> ```
> 
> 谢谢你

哦哦哦 不好意思，，task是个位置参数 我傻了。。。不过action='store_false'应该可以去掉吧~

**Comment by xiaoweidao** [comment]
> > > > > modify opts.py argparse~
> > > > > The demo.py tracking,ddd in demo.py tracking,ddd --load_model ../models/nuScenes_3Dtracking.pth --dataset nuscenes --pre_hm --track_thresh 0.1 --demo ../videos/nuscenes_mini.mp4 --test_focal_length 633 I don't know where to modify opts.py.
> > > > > Can you help me? thank you very much
> > > 
> > > 
> > > You should learn package argparse first。
> > > As for command like --load_model ../models/nuScenes_3Dtracking.pth，modify the parameter 'default' in self.parser.add_argument('--load_model', default='',help='path to pretrained model') (line 33 in opts.py):
> > > default="../models/nuScenes_3Dtracking.pth"
> > > As for command like --pre_hm , modify the parameter 'action' in self.parser.add_argument('--pre_hm', action='store_true')(line 207 in opts.py) : action = 'store_false'
> > > As for command tacking,ddd , modify the parameter 'default' in self.parser.add_argument('task', default='',
> > > help='ctdet | ddd | multi_pose| tracking or combined with ,')(line 13 in opts.py) : default = "tacking,ddd"
> > > 我也是个新手，可以互相交流~
> > 
> > 
> > ```
> > self.parser.add_argument('--task',action='store_false', default='tracking,ddd',
> >                          help='ctdet | ddd | multi_pose '
> >                          '| tracking or combined with ,')（line 13 in opts.py）I changed this line of code, so it can run successfully. Thank you for your help！
> > ```
> > 
> > 
> >   
> >     
> >     
> > 
> >     
> >     
> > 
> >   
> > 
> > 
> > 谢谢你
> 
> 哦哦哦 不好意思，，task是个位置参数 我傻了。。。不过action='store_false'应该可以去掉吧~
对对对，可以去掉，我直接加上设为默认就运行成功了，没考虑那么多，感谢！
