### ISSUE TITLE
import DCN failed in KITTI Tracking

### ISSUE THREAD

**Issue by Kasatusss** [xingyizhou/CenterTrack#21]
Thanks for your work!

I'm running *test.py* as it mentioned in *GettingStarted/KITTI Tracking*.
While running I'm getting an error **import DCN failed**.
I see that *src/lib/model/networks/dla.py* provides the following code:
```
try:
    from .DCNv2.dcn_v2 import DCN
except:
    print('import DCN failed')
    DCN = None
```
But there is no ` .DCNv2` lib in your repository, so DCN is always None.

Can anyone help me?

**Comment by xingyizhou** [comment]
Hi,
  You need to use `--recursive` when cloning this repo. Otherwise you will need to install DCNv2 manually from [here](https://github.com/xingyizhou/CenterTrack/blob/master/.gitmodules#L13).

**Comment by Kasatusss** [comment]
Thanks!

If anyone will install DCNv2 manually, you should build it after clonning repository.
For Google Collab try: `!/usr/bin/perl ./make.sh`

**Comment by bryanbocao** [comment]
Try using Docker:
https://github.com/bryanbocao/CenterTrack/blob/master/readme/Docker.md
https://github.com/xingyizhou/CenterTrack/pull/290

# Run CenterTrack using Docker

### DCNv2 Compilation Issue Fixed
```
docker pull bryanbocao/centertrack
docker run -d --ipc=host --shm-size=16384m -it -v /:/share --gpus all --network=bridge bryanbocao/centertrack /bin/bash
docker ps -a
```

Check ```<CONTAINER_ID>```:
```
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                       PORTS                NAMES
89bb79551ccb   bryanbocao/centertrack   "/usr/local/bin/nvid…"   49 seconds ago   Up 38 seconds                6006/tcp, 8888/tcp   competent_northcutt
```
```
docker exec -it <CONTAINE_ID> /bin/bash
```

```
docker exec -it 89bb79551ccb /bin/bash
```

Inside the container:
```
cd /root/CenterTrack/src/lib/model/networks/DCNv2
python3 setup.py build develop
cd /root/CenterTrack/src/
python3 demo.py tracking,ddd --load_model ../models/nuScenes_3Dtracking.pth --dataset nuscenes --pre_hm --track_thresh 0.1 --demo ../videos/nuscenes_mini.mp4 --test_focal_length 633
```
The DCNv2 is built from [MatthewHowe_DCNv2](https://github.com/MatthewHowe/DCNv2). Thanks [MatthewHowe](https://github.com/MatthewHowe) for the contribution.
Then you should be able to see the results.

Go to ```/share``` to transfer data between the container and your root system.
