### ISSUE TITLE
pytorch version issue

### ISSUE THREAD

**Issue by zhangxiaoya** [xingyizhou/CenterTrack#22]
https://github.com/xingyizhou/CenterTrack/blob/8c5ab8df6c2b6074a8694bd5d44138607a06fa93/src/lib/model/networks/backbones/mobilenet.py#L14

I use torch 1.0.0 and torchvision 0.2.0
 torchvision 0.2.0 does not has `models.utils.load_state_dict_from_url`

And
'nuscenes-devkit' need pytorch version > 1.0
And
DCNv2 now support pytorch 1.x
[https://github.com/CharlesShang/DCNv2/](https://github.com/CharlesShang/DCNv2/)

**Comment by alxh87** [comment]
Try this: 
```
try:
    from torch.hub import load_state_dict_from_url
except ImportError:
    from torch.utils.model_zoo import load_url as load_state_dict_from_url
```

**Comment by zhangxiaoya** [comment]
@alxh87 thanks, I upgrade pytorch to 1.4 and work for me.

**Comment by xingyizhou** [comment]
Closing this as the issue was solved.
