### ISSUE TITLE
Problem with evaluate_tracking.py

### ISSUE THREAD

**Issue by Kasatusss** [xingyizhou/CenterTrack#23]
Hello!

While training DCNv2 on KITTI, got an error:
```
Traceback (most recent call last):
  File "tools/eval_kitti_track/evaluate_tracking.py", line 984, in <module>
    success = evaluate(result_sha,mail,split_version=split_version)
  File "tools/eval_kitti_track/evaluate_tracking.py", line 919, in evaluate
    t_sha=result_sha, mail=mail,cls=c,split_version=split_version)
  File "tools/eval_kitti_track/evaluate_tracking.py", line 103, in __init__
    with open(filename_test_mapping, "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: './tools/eval_kitti_track/data/tracking/evaluate_trackingDrive/CenterTrack/src/lib/../../exp/tracking/kitti_half/results_kitti_tracking/.seqmap'
```
So, I checked the `evaluate_tracking.py`:
There is something weird in filename `evaluate_tracking{split_vesrion}.seqmap`. It seems that this lib was called with wrong parameters: `split_version = sys.argv[2] if len(sys.argv) >= 3 else ''`

But I don't know why and what kind of lib calls this `evaluate_tracking.py`.

Can anyone help?

**Comment by Kasatusss** [comment]
I've found a solution. Your `CenterTrack_ROOT` shouldn't contain spaces in dir names.
Unfortunately, Google Drive is mounted as *"My Drive"* by default.

**Comment by Blair129** [comment]
> I've found a solution. Your `CenterTrack_ROOT` shouldn't contain spaces in dir names.
> Unfortunately, Google Drive is mounted as _"My Drive"_ by default.

Is there anyway to change "My Drive" ? I didn't find a way to rename it in google drive.
