### ISSUE TITLE
Something missing in 'convert_mot_det_to_results.py'

### ISSUE THREAD

**Issue by TTTREE** [xingyizhou/CenterTrack#26]
Hi,
First,' seqs = [s for s in os.listdir(DET_PATH) if '_det' in s]' , there is no '_det' in '../../data/mot17/'

Second, 'if not IS_THIRD_PARTY:' there is no 'IS_THIRD_PARTY'?

I just follow the commend in your description. 
Is there anything wrong?
Thanks a lot!

**Comment by TTTREE** [comment]
I run the test of mot17 successfully. I modify the code above.

**Comment by Blair129** [comment]
> I run the test of mot17 successfully. I modify the code above.

I‘ m facing the same problem, could you show me how you modify the code? thx

**Comment by xingyizhou** [comment]
Sorry I note there is a version issue in the convert public detection code. I will fix it within a day. However you can still train the MOT models without using this. The public detections are only used in evaluation (public-detection mode).

**Comment by TTTREE** [comment]
> 
> 
> > I run the test of mot17 successfully. I modify the code above.
> 
> I‘ m facing the same problem, could you show me how you modify the code? thx

It seems the author fixed the problem. You can try it again.

**Comment by TTTREE** [comment]
> 
> 
> Sorry I note there is a version issue in the convert public detection code. I will fix it within a day. However you can still train the MOT models without using this. The public detections are only used in evaluation (public-detection mode).

Thank you very much!

**Comment by Blair129** [comment]
> Sorry I note there is a version issue in the convert public detection code. I will fix it within a day. However you can still train the MOT models without using this. The public detections are only used in evaluation (public-detection mode).

Thank you, I run it successfully.

**Comment by troylhy1991** [comment]
public detection seems not working. Have to create val_half_det.json in data/mot17/results/ folder.

However, public detection val_half yields 67.3% MOTA rather than 63.1%,  not sure why
![image](https://user-images.githubusercontent.com/14168265/80658609-6460f200-8a3b-11ea-9917-3d35a8471f33.png)

**Comment by TTTREE** [comment]
> 
> 
> public detection seems not working. Have to create val_half_det.json in data/mot17/results/ folder.
> 
> However, public detection val_half yields 67.3% MOTA rather than 63.1%, not sure why
> ![image](https://user-images.githubusercontent.com/14168265/80658609-6460f200-8a3b-11ea-9917-3d35a8471f33.png)

Could you please show more details? How did u ran the code with public detection?
