### ISSUE TITLE
MOT17 evaluation get error with no ground truth

### ISSUE THREAD

**Issue by consilium538** [xingyizhou/CenterTrack#27]
When try to evaluation MOT17 dataset with d0d9561a51a1a02da3036835ba6c130225f3ded4, this error occur

> --gt_type _val_half
> gt_type _val_half
> gt_files []
> 11:48:20 INFO - Found 0 groundtruths and 7 test files.
> 11:48:20 INFO - Available LAP solvers ['lapsolver', 'lap', 'scipy', 'munkres']
> 11:48:20 INFO - Default LAP solver 'lapsolver'
> 11:48:20 INFO - Loading files.
> 11:48:20 WARNING - No ground truth for MOT17-13-FRCNN, skipping.
> 11:48:20 WARNING - No ground truth for MOT17-09-FRCNN, skipping.
> 11:48:20 WARNING - No ground truth for MOT17-05-FRCNN, skipping.
> 11:48:20 WARNING - No ground truth for MOT17-04-FRCNN, skipping.
> 11:48:20 WARNING - No ground truth for MOT17-02-FRCNN, skipping.
> 11:48:20 WARNING - No ground truth for MOT17-10-FRCNN, skipping.
> 11:48:20 WARNING - No ground truth for MOT17-11-FRCNN, skipping.
> 11:48:20 INFO - Running metrics
> /home/dhk/.pyenv/versions/3.7.6/envs/.venv/lib/python3.7/site-packages/motmetrics/mot.py:243: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
>   idx = pd.MultiIndex(levels=[[],[]], labels=[[],[]], names=['FrameId','Event'])
> /home/dhk/.pyenv/versions/3.7.6/envs/.venv/lib/python3.7/site-packages/motmetrics/metrics.py:302: RuntimeWarning: invalid value encountered in long_scalars
>   return num_detections / num_objects
> /home/dhk/.pyenv/versions/3.7.6/envs/.venv/lib/python3.7/site-packages/motmetrics/metrics.py:298: RuntimeWarning: invalid value encountered in long_scalars
>   return num_detections / (num_false_positives + num_detections)
> /home/dhk/.pyenv/versions/3.7.6/envs/.venv/lib/python3.7/site-packages/motmetrics/metrics.py:294: RuntimeWarning: invalid value encountered in long_scalars
>   return 1. - (num_misses + num_switches + num_false_positives) / num_objects
> /home/dhk/.pyenv/versions/3.7.6/envs/.venv/lib/python3.7/site-packages/motmetrics/metrics.py:290: RuntimeWarning: invalid value encountered in double_scalars
>   return df.noraw['D'].sum() / num_detections
>         Rcll Prcn GT   MT   PT   ML   FP   FN  IDs   FM MOTA MOTP num_objects
> OVERALL nan% nan%  0 nan% nan% nan% nan% nan% nan% nan% nan%  nan           0
> Traceback (most recent call last)
> ...
> IndexError: arrays used as indices must be of integer (or boolean) type

This part is suspicious. https://github.com/xingyizhou/CenterTrack/blob/d0d9561a51a1a02da3036835ba6c130225f3ded4/src/lib/dataset/datasets/mot.py#L93-L96

There may be two solutions. First one is edit mot.py to match data folder structure, specifically, change trainval to train. Second one is change data folder modification script to match mot.py

**Comment by xingyizhou** [comment]
Thank you for pointing it out! I have fixed it.
