### ISSUE TITLE
Offset not used?

### ISSUE THREAD

**Issue by ammaddd** [xingyizhou/CenterTrack#28]
Hello

Firstly, I appreciate your work

1) Is offset being used in tracking. I can't find it in tracking.py file?. Is the offset supposed to be 0 in the implemented code? 

2) When i use heatmap (pre_hm) false predictions after some frames start accumulating (this does not happen when i use same model without pre_hm but model was trained with pre_hm). Is the pre_hm not robust ?Did you face any similar issues like the one in below images? (trying to do for vehicles)(Model is trained for 18 epochs now)

![2107](https://user-images.githubusercontent.com/49341767/79440727-c8bd9380-7fef-11ea-970d-44419b616df2.jpg)

**Comment by xingyizhou** [comment]
Hi, 
  Sorry for the confusion, the tracking offset is named as `tracking` in the code, and is used in [this line](https://github.com/xingyizhou/CenterTrack/blob/master/src/lib/utils/tracker.py#L33) for tracking.

**Comment by xingyizhou** [comment]
For the second question, if you are training model for your own dataset, you can increase the simulated false positive rate by `--fp_disturb x`. Ideally `x` should match the false positive rate when using a baseline detector under your output threshold. If you don't want to train, an easier way is to increase the threshold for feeding the detection to the previous heatmap by setting `--pre_thresh`. Usually, it needs to be higher than `--thack_thresh`. See the last section of our supplementary about how these hyper-parameters interact in MOT17.

**Comment by ammaddd** [comment]
Thank you for your informative response.
