### ISSUE TITLE
 how to Calculation ct with c++  inferfor 3d detction 

### ISSUE THREAD

**Issue by lyxbyr** [xingyizhou/CenterTrack#37]
Hi thanks  your great works
Calculation ct(use `  ct = [(bbox[0] + bbox[2]) / 2, (bbox[1] + bbox[3]) / 2])` with c++  infer（item['loc'], item['rot_y']　 for 3d detction is right? because i don not how to calculation dets['bboxes'][i][j]　 only use this instead　

the calculation of item ('loc'), item ('rot_y') needs to get ct value, depending on whether the output of the network has amodel_offset branches, ct calculation method is different, for the 3d detection model has amodel_offest branch, execute the following code internal if statement, this ct_output = dets['bboxes'][i][j].reshape(2, 2).mean(axis=0)  dets['bboxes'][i][j]  is a series of conversions through heap topk, 
and if want to get this value, have to write a post-processing operation (topk, a series of conversions) with C++  to get the  dets['bboxes'][i][j] ? 

` 
if 'amodel_offset' in dets and len(dets['amodel_offset'][i]) > j:
      ct_output = dets['bboxes'][i][j].reshape(2, 2).mean(axis=0)
      amodel_ct_output = ct_output + dets['amodel_offset'][i][j]
      ct = transform_preds_with_trans(
        amodel_ct_output.reshape(1, 2), trans).reshape(2).tolist()
      #print(ct)
    else:
        bbox = item['bbox']
        print(bbox)
        ct = [(bbox[0] + bbox[2]) / 2, (bbox[1] + bbox[3]) / 2]
    item['ct'] = ct
    item['loc'], item['rot_y'] = ddd2locrot(
      ct, item['alpha'], item['dim'], item['dep'], calibs[i]) `

**Comment by xingyizhou** [comment]
Sorry I didn't get your question. Are you asking how to translate the code from python to c++? If so, just go into each subfunction and translate them.  The only tricky line should be `transform_preds_with_trans`, which needs an affine-trainsformation matrix from openCV. It should be included in openCV C++ version.
