### ISSUE TITLE
rotation_y loss in 3d

### ISSUE THREAD

**Issue by 123alaa** [xingyizhou/CenterTrack#39]
Hi @xingyizhou 

I trained Center net and center track for a lot of time, and the minimal loss that I can get from rotation loss is ~1.3. Is this good? I thought the perfect result to be near 0 right?

I investigated the code and make some manipulation, the minimal results are like this (losses.py).

In case all the tensor are zeros.
loss_bin1 0.6931
loss_bin2 0.6931
loss_res 0
some 1.38

But in the normal experiments, I get ~ 1.32,

What I should get? Do you have different results?

**Comment by xingyizhou** [comment]
My rot_loss on nuScenes is about 1.6. I usually don't look at the absolute loss value, as it doesn't indicate anything about the performance. Did you get an expected final mAP?

**Comment by xingyizhou** [comment]
Closing for now. Feel free to reopen.
