### ISSUE TITLE
OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)' OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'

### ISSUE THREAD

**Issue by Stephenfang51** [xingyizhou/CenterTrack#40]
anyone like me can't output video properly?

default setting, the error shows
`OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)' OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'`

I also tried the following

`v2.VideoWriter_fourcc(*'mp4v)`

still can't yield  video properly.

**Comment by xingyizhou** [comment]
This seems an opencv issue. Make sure you installed opencv by `pip install opencv-python`. If that's the case, can you load a video correctly using openCV?

**Comment by Stephenfang51** [comment]
> This seems an opencv issue. Make sure you installed opencv by `pip install opencv-python`. If that's the case, can you load a video correctly using openCV?
Thanks for the reply @xingyizhou 

We can forget about the problem above
but there is another error happend

here is my command code
`python demo.py tracking --load_model ../models/coco_tracking.pth --demo ../videos/nuscenes_mini.mp4 --save_video
`
it seems like the loading was correct for the first 40 frames, but in the last maybe not the last frame, opencv loads NoneType.

I am pretty sure I installed opencv through `pip install opencv-python` and the version is 4.2

what do you think ?

```
<class 'numpy.ndarray'>
<class 'dict'>
frame 39 |tot 0.036s |load 0.000s |pre 0.011s |net 0.021s |dec 0.002s |post 0.001s |merge 0.000s |display 0.003s |
write is ok
<class 'numpy.ndarray'>
<class 'dict'>
frame 40 |tot 0.036s |load 0.000s |pre 0.011s |net 0.021s |dec 0.002s |post 0.001s |merge 0.000s |display 0.003s |
write is ok
<class 'NoneType'>
Traceback (most recent call last):
  File "demo.py", line 122, in <module>
    demo(opt)
  File "demo.py", line 66, in demo
    ret = detector.run(img, input_meta)
  File "/home/workplace/centertrack/src/lib/detector.py", line 69, in run
    image = image_or_path_or_tensor['image'][0].numpy()
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Stephenfang51** [comment]
and I tried skipping all the last frame, no errors but the yielded video is blank, the file is only 258B which means output incorrectly. Could you provided me the `opencv-python` version you tested on ?

**Comment by lyxbyr** [comment]
add this --resize_video  .mp4.mp4 is ok

**Comment by Stephenfang51** [comment]
> add this --resize_video .mp4.mp4 is ok

yup, thanks I just though the default setting will be fine ....

**Comment by sisrfeng** [comment]
> add this --resize_video .mp4.mp4 is ok

add this：
--resize_video

**Comment by AnnetGeorge** [comment]
Hello, were you able to solve this problem? I tried specifying video_h and video_w as well as the resize option, but both don't seem to work. I also get a .mp4.mp4 file - did you change this to .mp4?

**Comment by P0i0lot** [comment]
> > 添加这个 --resize_video .mp4.mp4 就可以了
> 
> 添加这个： --resize_video

您好，这个在哪里添加啊
