### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by monsters-s** [xingyizhou/CenterTrack#42]
when I use python demo.py tracking --load_model ../models/coco_tracking.pth --demo ../aaa(aaa is my pictures),there is no result,and the terminal said
Running tracking
Using tracking threshold for out threshold! 0.3
Fix size testing.
training chunk_sizes: [32]
input h w: 512 512
heads {'hm': 80, 'reg': 2, 'wh': 2, 'tracking': 2}
weights {'hm': 1, 'reg': 1, 'wh': 0.1, 'tracking': 1}
head conv {'hm': [256], 'reg': [256], 'wh': [256], 'tracking': [256]}
Creating model...
Using node type: (<class 'model.networks.dla.DeformConv'>, <class 'model.networks.dla.DeformConv'>)
Warning: No ImageNet pretrain!!
loaded ../models/coco_tracking.pth, epoch 70
Drop parameter base.pre_hm_layer.0.weight.
Drop parameter base.pre_hm_layer.1.weight.
Drop parameter base.pre_hm_layer.1.bias.
Drop parameter base.pre_hm_layer.1.running_mean.
Drop parameter base.pre_hm_layer.1.running_var.
Drop parameter base.pre_hm_layer.1.num_batches_tracked.
Initialize tracking!
Traceback (most recent call last):
  File "demo.py", line 118, in <module>
    demo(opt)
  File "demo.py", line 90, in demo
    ret = detector.run(image_name)
  File "/home/lsw/CenterTrack/src/lib/detector.py", line 94, in run
    self.tracker.init_track(meta['pre_dets'])
KeyError: 'pre_dets'
Segmentation fault (core dumped)

what is the problem?

**Comment by monsters-s** [comment]
And when I use python demo.py tracking --load_model ../models/coco_tracking.pth --demo ../videos

there is also no result,and the terminal is:
Running tracking
Using tracking threshold for out threshold! 0.3
Fix size testing.
training chunk_sizes: [32]
input h w: 512 512
heads {'hm': 80, 'reg': 2, 'wh': 2, 'tracking': 2}
weights {'hm': 1, 'reg': 1, 'wh': 0.1, 'tracking': 1}
head conv {'hm': [256], 'reg': [256], 'wh': [256], 'tracking': [256]}
Creating model...
Using node type: (<class 'model.networks.dla.DeformConv'>, <class 'model.networks.dla.DeformConv'>)
Warning: No ImageNet pretrain!!
loaded ../models/coco_tracking.pth, epoch 70
Drop parameter base.pre_hm_layer.0.weight.
Drop parameter base.pre_hm_layer.1.weight.
Drop parameter base.pre_hm_layer.1.bias.
Drop parameter base.pre_hm_layer.1.running_mean.
Drop parameter base.pre_hm_layer.1.running_var.
Drop parameter base.pre_hm_layer.1.num_batches_tracked.
Segmentation fault (core dumped)

And there is no videos.Is this becuase I use xshell to use my linux computer?

**Comment by JoeyQWu** [comment]
Hi, guys,
How did you solve these problems ?

**Comment by monsters-s** [comment]
> Hi, guys,
> How did you solve these problems ?

centertrack didn't support demo for images and the video path is a video instead of a file.

**Comment by JoeyQWu** [comment]
what do you mean the video path is a video instead of a file?
I use the command "python demo.py tracking --dataset mot --pre_hm --track_thresh 0.1 --num_classes 1 --load_model /home/ubuntu/CenterTrack/exp/tracking/mot17_fulltrain/model_last.pth --demo /homeubuntu/CenterTrack/videos/nuscenes_mini.mp4"  but there is a problem that
`Traceback (most recent call last):
  File "demo.py", line 127, in <module>
    demo(opt)
  File "demo.py", line 82, in demo
    ret = detector.run(img)
  File "/home/ubuntu/CenterTrack/src/lib/detector.py", line 110, in run
    self.tracker.tracks, meta, with_hm=not self.opt.zero_pre_hm)
  File "/home/ubuntu/CenterTrack/src/lib/detector.py", line 293, in _get_additional_inputs
    output_inds = torch.from_numpy(output_inds).to(self.opt.device)
RuntimeError: sizes must be non-negative
`
I have no idea what I should do to fix this problem,
Could you tell me ? thanks a lot.

**Comment by monsters-s** [comment]
> what do you mean the video path is a video instead of a file?
> I use the command "python demo.py tracking --dataset mot --pre_hm --track_thresh 0.1 --num_classes 1 --load_model /home/ubuntu/CenterTrack/exp/tracking/mot17_fulltrain/model_last.pth --demo /homeubuntu/CenterTrack/videos/nuscenes_mini.mp4" but there is a problem that
> `Traceback (most recent call last): File "demo.py", line 127, in <module> demo(opt) File "demo.py", line 82, in demo ret = detector.run(img) File "/home/ubuntu/CenterTrack/src/lib/detector.py", line 110, in run self.tracker.tracks, meta, with_hm=not self.opt.zero_pre_hm) File "/home/ubuntu/CenterTrack/src/lib/detector.py", line 293, in _get_additional_inputs output_inds = torch.from_numpy(output_inds).to(self.opt.device) RuntimeError: sizes must be non-negative `
> I have no idea what I should do to fix this problem,
> Could you tell me ? thanks a lot.

sorry.I haven't use this model for demo,I only use coco_tracking.pth as :python demo.py tracking --load_model ../models/coco_tracking.pth --demo /path/to/image/or/folder/or/video

**Comment by auniquesun** [comment]
@monsters-s  I encounter same problem as you. Can you show us a specific example surroundded by the double quotes? rather than --demo **"**/path/to/image/or/folder/or/video**"**

**Comment by alexrider1105** [comment]
Was there ever a conclusion to this issue? I also am facing the same issue.
When I run 
python demo.py tracking,ddd --load_model ../models/nuScenes_3Dtracking.pth --dataset nuscenes --pre_hm --track_thresh 0.1 --demo ../videos/nuscenes_mini.mp4 --test_focal_length 633
I get the following:
/home/shihkuan/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/sklearn/utils/linear_assignment_.py:21: DeprecationWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  DeprecationWarning)
Running tracking
Using tracking threshold for out threshold! 0.1
Fix size testing.
training chunk_sizes: [32]
input h w: 448 800
heads {'hm': 10, 'reg': 2, 'wh': 2, 'tracking': 2, 'dep': 1, 'rot': 8, 'dim': 3, 'amodel_offset': 2}
weights {'hm': 1, 'reg': 1, 'wh': 0.1, 'tracking': 1, 'dep': 1, 'rot': 1, 'dim': 1, 'amodel_offset': 1}
head conv {'hm': [256], 'reg': [256], 'wh': [256], 'tracking': [256], 'dep': [256], 'rot': [256], 'dim': [256], 'amodel_offset': [256]}
Creating model...
Using node type: (<class 'model.networks.dla.DeformConv'>, <class 'model.networks.dla.DeformConv'>)
Warning: No ImageNet pretrain!!
loaded ../models/nuScenes_3Dtracking.pth, epoch 70
Initialize tracking!
Segmentation fault (core dumped)

**Comment by hdm8809** [comment]
use absolute path for vedio path
