### ISSUE TITLE
a issue of test.py

### ISSUE THREAD

**Issue by monsters-s** [xingyizhou/CenterTrack#43]
I use python test.py tracking --exp_id mot17_half --dataset mot --dataset_version 17halfval --pre_hm --ltrb_amodal --track_thresh 0.4 --pre_thresh 0.5 --load_model ../models/mot17_half.pth

Bad key "text.kerning_factor" on line 4 in
/home/lsw/anaconda3/envs/CenterNet/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
Running tracking
Using tracking threshold for out threshold! 0.4
Fix size testing.
training chunk_sizes: [32]
input h w: 544 960
heads {'hm': 1, 'reg': 2, 'wh': 2, 'tracking': 2, 'ltrb_amodal': 4}
weights {'hm': 1, 'reg': 1, 'wh': 0.1, 'tracking': 1, 'ltrb_amodal': 0.1}
head conv {'hm': [256], 'reg': [256], 'wh': [256], 'tracking': [256], 'ltrb_amodal': [256]}
Namespace(K=100, add_05=False, amodel_offset_weight=1, arch='dla_34', aug_rot=0, backbone='dla34', batch_size=32, chunk_sizes=[32], custom_dataset_ann_path='', custom_dataset_img_path='', data_dir='/home/lsw/centertrack/src/lib/../../data', dataset='mot', dataset_version='17halfval', debug=0, debug_dir='/home/lsw/centertrack/src/lib/../../exp/tracking/mot17_half/debug', debugger_theme='white', demo='', dense_reg=1, dep_weight=1, depth_scale=1, dim_weight=1, dla_node='dcn', down_ratio=4, efficient_level=0, eval_val=False, exp_dir='/home/lsw/centertrack/src/lib/../../exp/tracking', exp_id='mot17_half', fix_res=True, fix_short=-1, flip=0.5, flip_test=False, fp_disturb=0, gpus=[0], gpus_str='0', head_conv={'hm': [256], 'reg': [256], 'wh': [256], 'tracking': [256], 'ltrb_amodal': [256]}, head_kernel=3, heads={'hm': 1, 'reg': 2, 'wh': 2, 'tracking': 2, 'ltrb_amodal': 4}, hm_disturb=0, hm_hp_weight=1, hm_weight=1, hp_weight=1, hungarian=False, ignore_loaded_cats=[], input_h=544, input_res=960, input_w=960, keep_res=False, kitti_split='3dop', load_model='../models/mot17_half.pth', load_results='', lost_disturb=0, lr=0.000125, lr_step=[60], ltrb=False, ltrb_amodal=True, ltrb_amodal_weight=0.1, ltrb_weight=0.1, map_argoverse_id=False, master_batch_size=32, max_age=-1, max_frame_dist=3, model_output_list=False, msra_outchannel=256, neck='dlaup', new_thresh=0.4, nms=False, no_color_aug=False, no_pause=False, no_pre_img=False, non_block_test=False, not_cuda_benchmark=False, not_idaup=False, not_max_crop=False, not_prefetch_test=False, not_rand_crop=False, not_set_cuda_env=False, not_show_bbox=False, not_show_number=False, num_classes=1, num_epochs=70, num_head_conv=1, num_iters=-1, num_layers=101, num_stacks=1, num_workers=4, nuscenes_att=False, nuscenes_att_weight=1, off_weight=1, optim='adam', out_thresh=0.4, output_h=136, output_res=240, output_w=240, pad=31, pre_hm=True, pre_img=True, pre_thresh=0.5, print_iter=0, prior_bias=-4.6, public_det=False, qualitative=False, reg_loss='l1', reset_hm=False, resize_video=False, resume=False, reuse_hm=False, root_dir='/home/lsw/centertrack/src/lib/../..', rot_weight=1, rotate=0, same_aug_pre=False, save_all=False, save_dir='/home/lsw/centertrack/src/lib/../../exp/tracking/mot17_half', save_framerate=30, save_img_suffix='', save_imgs=[], save_point=[90], save_results=False, save_video=False, scale=0, seed=317, shift=0, show_track_color=False, skip_first=-1, tango_color=False, task='tracking', test=False, test_dataset='mot', test_focal_length=-1, test_scales=[1.0], track_thresh=0.4, tracking=True, tracking_weight=1, trainval=False, transpose_video=False, use_kpt_center=False, use_loaded_results=False, val_intervals=10000, velocity=False, velocity_weight=1, video_h=512, video_w=512, vis_gt_bev='', vis_thresh=0.3, weights={'hm': 1, 'reg': 1, 'wh': 0.1, 'tracking': 1, 'ltrb_amodal': 0.1}, wh_weight=0.1, zero_pre_hm=False, zero_tracking=False)
fatal: No names found, cannot describe anything.
Traceback (most recent call last):
  File "test.py", line 195, in <module>
    prefetch_test(opt)
  File "test.py", line 59, in prefetch_test
    Logger(opt)
  File "/home/lsw/centertrack/src/lib/logger.py", line 33, in __init__
    subprocess.check_output(["git", "describe"])))
  File "/home/lsw/anaconda3/envs/CenterTrack/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/lsw/anaconda3/envs/CenterTrack/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'describe']' returned non-zero exit status 128.

what should I do?
Should I use MOT17 datesets? or where I should put the MOT17?

**Comment by lisongze** [comment]
you  may use ```git describe --always``` instead.
```subprocess.check_output(["git", "describe", "--always"])))```

**Comment by monsters-s** [comment]
> git describe --always

Thank you for your answer.But I don't know how to use this.I use 'git describe --always' directly and the result is 'deaadf7'.Could you speak detailed method?

**Comment by monsters-s** [comment]
@lisongze 
Thank you for your answer.But I don't know how to use this.I use 'git describe --always' directly and the result is 'deaadf7'.Could you speak detailed method?

**Comment by lisongze** [comment]
> @lisongze
> Thank you for your answer.But I don't know how to use this.I use 'git describe --always' directly and the result is 'deaadf7'.Could you speak detailed method?

change line 33 in /home/lsw/centertrack/src/lib/logger.py to 
```subprocess.check_output(["git", "describe", "--always"])))```

**Comment by monsters-s** [comment]
@lisongze  yes,that's right.
But it has a new problem
Using MOT 17 17halfval
ann_file val_half.json
==> initializing val data from /home/lsw/centertrack_new/src/lib/../../data/mot17/annotations/val_half.json, 
 images from /home/lsw/centertrack_new/src/lib/../../data/mot17/train ...
loading annotations into memory...
Traceback (most recent call last):
  File "test.py", line 195, in <module>
    prefetch_test(opt)
  File "test.py", line 62, in prefetch_test
    dataset = Dataset(opt, split)
  File "/home/lsw/centertrack_new/src/lib/dataset/datasets/mot.py", line 40, in __init__
    super(MOT, self).__init__(opt, split, ann_path, img_dir)
  File "/home/lsw/centertrack_new/src/lib/dataset/generic_dataset.py", line 63, in __init__
    self.coco = coco.COCO(ann_path)
  File "/home/lsw/anaconda3/envs/py37/lib/python3.7/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/lsw/centertrack_new/src/lib/../../data/mot17/annotations/val_half.json'

It means I haven't data/mot17/annotations/val_half.json.But I download the MOT17 datesets, it dosen't have it,and where I should put the images of MOT17 in ?

**Comment by xingyizhou** [comment]
Can you make sure you have followed readme/DATA.md to create the annotation file?

**Comment by monsters-s** [comment]
@xingyizhou I think the last line of get_mot_17.sh is 'python convert_mot_det_to_results.py' instead of 'python convert_mot_det_to_results'?
