### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by monsters-s** [xingyizhou/CenterTrack#47]
when I use demo.py to run a avi ,a problem happened at the last frame:
Traceback (most recent call last):
  File "demo.py", line 126, in <module>
    demo(opt)
  File "demo.py", line 65, in demo
    ret = detector.run(img, input_meta)
  File "/home/ppp/centertrack_new/src/lib/detector.py", line 66, in run
    image = image_or_path_or_tensor['image'][0].numpy()
TypeError: 'NoneType' object is not subscriptable

what should I do?

**Comment by bamps53** [comment]
Did you change some part of code? It automatically escape if image is None by trying to imshow and then escape by default.

**Comment by monsters-s** [comment]
@bamps53   yes,I have change three places of 'imshow'.Because run demo will have three windows which are previous,input and generic.Now I have delete these 'imshow' and when I use demo.py ,it won't show three windows.

**Comment by monsters-s** [comment]
@bamps53 But I still have this question

**Comment by bamps53** [comment]
Changing this part to like that works for me.
https://github.com/xingyizhou/CenterTrack/blob/deaadf788b7921c0fd3d405ff7556f459ba0a98c/src/demo.py#L51-L55
```
        if img is None:
          print('FINISH!')
          save_and_exit(opt, out, results, out_name)
```

**Comment by monsters-s** [comment]
@bamps53 Thanks.I have solve it.

**Comment by xingyizhou** [comment]
Closing as issue solved.
