### ISSUE TITLE
how to train net  by adding Semantic segmentation branch ?

### ISSUE THREAD

**Issue by lyxbyr** [xingyizhou/CenterTrack#54]
thanks your amazing works
i have add Semantic segmentation branch in net, and want to  finetune in this weight(nuScenes_3Ddetection_e140.pth ) Want more output of semantic segmentation in the network but i don not how to definition my dataset in your dataset factory and don not know how to train Semantic segmentation branch? (frozen others output, only train Semantic segmentation branch ?)

**Comment by xingyizhou** [comment]
Thank you for your interest. I would say you need to expect many code changes. I haven't worked on Semantic segmentation so I am not able to give more specific suggestions.
