### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.utils.linear_assignment_'

### ISSUE THREAD

**Issue by vhnamgau** [xingyizhou/CenterTrack#64]
/CenterTrack/src/lib/utils/tracker.py", line 2, in <module>
    from sklearn.utils.linear_assignment_ import  linear_assignment
ModuleNotFoundError: No module named 'sklearn.utils.linear_assignment_'

---------
/CenterTrack/src$ python
Python 3.6.10 (default, Dec 19 2019, 23:04:32) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sklearn.utils import warnings
>>> from sklearn.utils import linear_assignment_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'linear_assignment_'
>>> 
----------------
pip list
Package             Version  Location
------------------- -------- -----------------------------------------------------------
attrs               19.3.0
backcall            0.1.0
bleach              3.1.5
cachetools          4.1.0
cycler              0.10.0
Cython              0.29.17
DCNv2               0.1      /media/iot-2/namvh/CenterTrack/src/lib/model/networks/DCNv2
decorator           4.4.2
defusedxml          0.6.0
descartes           1.1.0
dill                0.2.7.1
easydict            1.9
entrypoints         0.3
fire                0.3.1
flake8              3.8.1
flake8-import-order 0.18.1
future              0.18.2
importlib-metadata  1.6.0
ipykernel           5.2.1
ipython             7.14.0
ipython-genutils    0.2.0
ipywidgets          7.5.1
jedi                0.17.0
Jinja2              2.11.2
joblib              0.14.1
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.3
jupyter-console     6.1.0
jupyter-core        4.6.3
kiwisolver          1.2.0
llvmlite            0.32.1
MarkupSafe          1.1.1
matplotlib          3.2.1
mccabe              0.6.1
mistune             0.8.4
more-itertools      8.2.0
motmetrics          1.1.3
nbconvert           5.6.1
nbformat            5.0.6
notebook            6.0.3
numba               0.49.1
numpy               1.18.4
nuscenes-devkit     1.0.8
opencv-python       4.2.0.34
packaging           20.3
pandas              1.0.3
pandocfilters       1.4.2
parso               0.7.0
patsy               0.5.1
pexpect             4.8.0
pickleshare         0.7.5
Pillow              6.2.1
pip                 20.1
pluggy              0.13.1
progress            1.5
prometheus-client   0.7.1
prompt-toolkit      3.0.5
ptyprocess          0.6.0
py                  1.8.1
py-cpuinfo          5.0.0
pycodestyle         2.6.0
pyflakes            2.2.0
PyFunctional        1.3.0
Pygments            2.6.1
pyparsing           2.4.7
pyquaternion        0.9.5
pyrsistent          0.16.0
pytest              5.4.2
pytest-benchmark    3.2.3
python-dateutil     2.8.1
pytz                2020.1
PyYAML              5.3.1
pyzmq               19.0.1
qtconsole           4.7.3
QtPy                1.9.0
scikit-learn        0.23.0
scipy               1.4.1
seaborn             0.10.1
Send2Trash          1.5.0
setuptools          40.6.2
Shapely             1.7.0
six                 1.14.0
sklearn             0.0
statsmodels         0.11.1
tabulate            0.8.7
termcolor           1.1.0
terminado           0.8.3
testpath            0.4.4
threadpoolctl       2.0.0
torch               1.5.0
torchvision         0.6.0
tornado             6.0.4
tqdm                4.46.0
traitlets           4.3.3
wcwidth             0.1.9
webencodings        0.5.1
wheel               0.34.2
widgetsnbextension  3.5.1
xmltodict           0.12.0
zipp                3.1.0

--------

**Comment by ZUB41R** [comment]
# Deprecation warning for module
warnings.warn(
    "The linear_assignment_ module is deprecated in 0.21 "
    "and will be removed from 0.23. Use "
    "scipy.optimize.linear_sum_assignment instead.",
    FutureWarning)
I tried to use **scipy.optimize.linear_sum_assignment** instead but could at first try. Later downgraded to scikit-learn==0.21.0.

**Comment by vhnamgau** [comment]
> # Deprecation warning for module
> warnings.warn(
> "The linear_assignment_ module is deprecated in 0.21 "
> "and will be removed from 0.23. Use "
> "scipy.optimize.linear_sum_assignment instead.",
> FutureWarning)
> I tried to use **scipy.optimize.linear_sum_assignment** instead but faced errors at first try. Later downgraded to scikit-learn==0.21.0.

Thank you very much!
