### ISSUE TITLE
The test on CrowdHuman dataset.

### ISSUE THREAD

**Issue by TTTREE** [xingyizhou/CenterTrack#69]
Hi!
Thanks for your great work!
I am studying your paper and trying to eval the detection results on crowdhuman dataset using CenterTrack. In actually, it is CenterNet because I use the task = 'ctdet'. 
There are some scripts in dataset/crowdhuman.py
 
![图片](https://user-images.githubusercontent.com/37862384/82026306-2e6f6f00-96c5-11ea-874d-8adef7186710.png)
However, There isn't any tools/crowdhuman_eval/demo.py.
So could you please provide these files or give me some advice about how can I eval crowdhuman_val using CenterNet.
Thanks a lot!!

**Comment by xingyizhou** [comment]
Hi these should be the original evaluation scripts of the CrowdHuman dataset. We didn't intend to evaluate on CrowdHuman. The results are expected to be bad, as we use a small input resolution 512x512, which many of the CrowdHuman images are large (>1000x1000).

**Comment by TTTREE** [comment]
> 
> 
> Hi these should be the original evaluation scripts of the CrowdHuman dataset. We didn't intend to evaluate on CrowdHuman. The results are expected to be bad, as we use a small input resolution 512x512, which many of the CrowdHuman images are large (>1000x1000).

Thanks for your reply!
