### ISSUE TITLE
Issues on testing demo.py with the pre-trained models

### ISSUE THREAD

**Issue by rose-jinyang** [xingyizhou/CenterTrack#70]
Hello
How are you?
Thanks for contributing this project.
The demo.py works with the model _coco_tracking.pth_ and MOT16 test videos but the accuracy seems to be very poor.
and I tried to test demo.py with the model _mot17_fulltrain.pth_ and a MOT16 test video but I can not see any bounding box being tracked.
please let me know how to fix these issues.
Thanks

**Comment by JoeyQWu** [comment]
Hi, guys,
Have you fixed it ?

**Comment by xingyizhou** [comment]
This is because the MOT17 model has a different output channel (1) comparing to the default coco model (80). You need to add `--num_classes 1` when using MOT models.

**Comment by rose-jinyang** [comment]
Thanks for your reply.
