### ISSUE TITLE
Anyone successfully run this repo on ubuntu 18?

### ISSUE THREAD

**Issue by sisrfeng** [xingyizhou/CenterTrack#72]
After compiling DCNv2 successful, still can not import DCN #53
My environment:
Ubuntu 18.04, with Anaconda Python 3.6, CUDA 10.0.130, and PyTorch v1.0.0
I wonder if I need to shift to ubuntu 16, which may cost some time.
Many thx!

**Comment by edithzeng** [comment]
I'm on Ubuntu 18.04 with CUDA 10.0. Try install `torch==1.3.1+cu100`.

**Comment by xingyizhou** [comment]
Ubuntu 18.04 works for me too. Can you make sure your pytorch cuda version matches your environment cuda version?

**Comment by sisrfeng** [comment]
After uninstalling PyTorch v1.0.0 and use 1.4 instead , I can run the demo successfully.
Thx!
