### ISSUE TITLE
I trained the model with crowdhuman dataset, and the loss seems to converge.But it cannot detect any bbox in my video.

### ISSUE THREAD

**Issue by HAOCHENYE** [xingyizhou/CenterTrack#76]
Thanks for your great work! The model trained with MOT17 seems to perform well, and I trained the model with crowdhuman dataset using static image method. But I cannot find any bbox when I run demo.py, shoud I adjust some parameters?
Btw, the code in post_processed.py row 332,.why it is **‘break'** but  **’continue**‘?

**Comment by xingyizhou** [comment]
demo.py uses COCO dataset by default, which requires the last layer to be 80 categories. If you are using custom models, please make sure you have changed the last layer by `--num_class 1` and don't see any "skip loading xxx"  or "parameter not found xxx" in the log.
