### ISSUE TITLE
What is v value in tracker?

### ISSUE THREAD

**Issue by vneseresearcher** [xingyizhou/CenterTrack#89]
Can you show me or explain about v value in tracker. If I set max_age > 0 i receive error

**Comment by xingyizhou** [comment]
v is the velocity. You can simply make v = [0, 0] or v = [- tracking[0] * hyper_parameter, - tracking[1] * hyper_parameter]. v = [0, 0] works well for me.

**Comment by vneseresearcher** [comment]
Thanks a lot!
