### ISSUE TITLE
Can not save the demo results!

### ISSUE THREAD

**Issue by yinhai86924** [xingyizhou/CenterTrack#91]
can you tell me how to save the test demo video? thank you ! I add the --save video and add the ../results folder, however the output is default_nuscenes_mini.mp4,  but its size is 258 bytes

**Comment by Veronica1997** [comment]
I have the same problem with you .the output "default...mp4"doesn't have any test results on it. Have you solved the problem?

**Comment by yinhai86924** [comment]
> I have the same problem with you .the output "default...mp4"doesn't have any test results on it. Have you solved the problem?

I get a  default_nuscenes_mini.mp4 that shows the tracking results

**Comment by rkim27** [comment]
Try specifying the --video_h and --video_w arguments with your input video height and width

**Comment by yinhai86924** [comment]
thank you ! ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Russell&amp;nbsp;Kim&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月21日(星期天) 晚上11:12
收件人:&nbsp;&quot;xingyizhou/CenterTrack&quot;<CenterTrack@noreply.github.com&gt;;
抄送:&nbsp;&quot;yinhai86924&quot;<454960553@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xingyizhou/CenterTrack] Can not save the demo results! (#91)

**Comment by xingyizhou** [comment]
Thanks @rkim27 . Closing as issue solved.

**Comment by DICPZhou** [comment]
> can you tell me how to save the test demo video? thank you ! I add the --save video and add the ../results folder, however the output is default_nuscenes_mini.mp4, but its size is 258 bytes

Could you tell me how you solved the problem? Thank you very much

**Comment by RATHOD-SHUBHAM** [comment]
### This worked for me.
**In demo.py file**
_Line 48_: 
_change this_ 
  ```
if opt.save_video:
    fourcc = cv2.VideoWriter_fourcc(*'XVID')
    out = cv2.VideoWriter('results/{}.mp4'.format(
    opt.exp_id + '_' + out_name),fourcc, opt.save_framerate, (opt.video_w, opt.video_h))
```

_to this_

```
if opt.save_video:
    fourcc = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')
    out = cv2.VideoWriter('results/{}'.format(
      opt.exp_id + '_' + out_name),fourcc, opt.save_framerate, (
        opt.video_w, opt.video_h))
```

## Use this Command to run
 **Specify the height and width of video : --video_h 450 --video_w 800**
`!python src/demo.py tracking,ddd --load_model models/nuScenes_3Dtracking.pth --dataset nuscenes --pre_hm --track_thresh 0.1 --demo videos/nuscenes_mini.mp4 --test_focal_length 633 --video_h 450 --video_w 800 --save_video`
