### ISSUE TITLE
MOT17 half_val results

### ISSUE THREAD

**Issue by annonymous1212** [xingyizhou/CenterTrack#96]
Dear author,

I followed your training settings on MOT17 experiments and trained a model on MOT17 half_train. While I only got 63%~64% MOTA on the MOT17 half_val with two attempts, and I also played around the track_thresh and render_thresh, which failed to further improve. May I know if these results are expected? If not, are there any other details that we should note when training?

Thank you! Will appreciate it~

**Comment by xingyizhou** [comment]
Hi,
  Thank you for your experiments. This is not expected. I have repeated the same experiments on my machine for >5 times under the same setting, the lowest number I can find on my experimental sheet is 65.2 MOTA and the highest number is 67.1. Did you strictly follow the experimental [this](https://github.com/xingyizhou/CenterTrack/blob/master/experiments/mot17_half.sh) script? Make sure you haven't missed `--same_aug` or `--pre_hm`, these are likely to give ~2MOTA performance drop. Are you using 4 gpus or 2 gpus? Usually using 2 is slightly better.

**Comment by annonymous1212** [comment]
Thanks for your quick reply!

My torch version is 0.4.1, and here is the script that I was using:

Training: "python main.py tracking --exp_id mot17_half_baseline --dataset mot --dataset_version 17halftrain --pre_hm --ltrb_amodal --same_aug --hm_disturb 0.05 --lost_disturb 0.4 --fp_disturb 0.1 --gpus 0,1,2,3 --load_model ../models/crowdhuman.pth --batch_size 32" 

Testing: "python test.py tracking --exp_id mot17_half_baseline --dataset mot --dataset_version 17halfval --pre_hm --ltrb_amodal --track_thresh 0.1 --pre_thresh 0.5 --load_model ../exp/tracking/mot17_half_baseline/model_last.pth"

It should be exactly the same as the one you provided. I used 4 GPUs and the memory had been full when training 32 batches per iteration. Actually I am working on improving MOT over SOTA based on your great work, and the very first step is to reproduce your results. So I would be thankful if you could share with me more analyses if you have any.

Besides the above problem, I have a quick question regarding your algorithm. By looking into the code, the backbone takes the sum of the features of the previous image and the current image as input. Then I am curious about how the model can yield the detections in the current frame instead of those in the previous frame.

Sorry for such long text:) Appreciate it again!

**Comment by xingyizhou** [comment]
Will `--track_thresh 0.4` in testing work better? That's the default. One other possible issue is that you might need to disable cudnn bn for torch 0.4.1 (see [CenterNet installation](https://github.com/xingyizhou/CenterNet/blob/master/readme/INSTALL.md) for torch 0.4.1, the problem seems to dissolved for torch >= 1.0). Or you can try torch >= 1.0 to see if you can reproduce our results. 

For your question, all training annotations are provided for the current frame. It is not likely the model will learn to detect the previous frame without such supervision.

**Comment by annonymous1212** [comment]
Yes, I understand that in training we enforce the model to predict the current frame detections. While in testing the model takes the summation of the previous frame and the current frame as input instead of concatenation (the summation mixes up these two frames together). Then I am wondering how the model knows which image is the current frame.

**Comment by xingyizhou** [comment]
The current frame and the previous frame do NOT share the first layer. The model does know which one is the current frame.

**Comment by annonymous1212** [comment]
Got it. So the first layers encode the information indicating whether the image is the current frame. That's interesting and surprising that it can work!

**Comment by wujiyoung** [comment]
What is `--same_aug` used for ? I can not find out where it is used, I can only see `--same_aug_pre` in opt.

**Comment by lt573152873** [comment]
@wujiyoung  can you solve the question?
