### ISSUE TITLE
subprocess.CalledProcessError: Command '['git', 'describe']' returned non-zero exit status 128.

### ISSUE THREAD

**Issue by Veronica1997** [xingyizhou/CenterTrack#98]
When I train my own datasets in CenterTrack using"python main.py tracking --exp_id Bimage --dataset custom --custom_dataset_ann_path /home/eini/RY/Bimage/191204_16_cqupt_luo_04_COCO/annotations/train2017.json --custom_dataset_img_path /home/eini/RY/Bimage/191204_16_cqupt_luo_04_COCO/images/ --input_h 1080 --input_w 1920 --num_classes 1 --pre_hm --ltrb_amodal --same_aug --hm_disturb 0.05 --lost_disturb 0.4 --fp_disturb 0.1 --gpus 0,1"
I met the problem below:
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    main(opt)
  File "main.py", line 37, in main
    logger = Logger(opt)
  File "/home/eini/RY/CenterTrack/src/lib/logger.py", line 33, in __init__
    subprocess.check_output(["git", "describe"])))
  File "/home/eini/anaconda3/envs/CenterTrack/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/eini/anaconda3/envs/CenterTrack/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'describe']' returned non-zero exit status 128.

Has anyone met this problem before? What may cause this problem? 
Thank you !

**Comment by jasonlove521** [comment]
you  can do like this: 
 '''opt_file.write('==> commit hash: {}\n'.format(
        subprocess.check_output(["git", "describe"])))'''.
it works for me!

**Comment by Veronica1997** [comment]
> you can do like this:
> '''opt_file.write('==> commit hash: {}\n'.format(
> subprocess.check_output(["git", "describe"])))'''.
> it works for me!

Thank you very much!! it works for me too!

**Comment by xingyizhou** [comment]
Thanks @jasonlove521 . Closing as issue solved.

**Comment by ZackGoing** [comment]
> > you can do like this:
> > '''opt_file.write('==> commit hash: {}\n'.format(
> > subprocess.check_output(["git", "describe"])))'''.
> > it works for me!
> 
> Thank you very much!! it works for me too!

how does it work? how to implement  '''opt_file.write('==> commit hash: {}\n'.format(
> > subprocess.check_output(["git", "describe"])))'''

**Comment by JOSHUAWENJZ** [comment]
@ZackGoing Just comment out thesse lines. 2333

**Comment by Tangzixia** [comment]
you can change  subprocess 355 line ,"check=True" to "check=False" , it works for me.

**Comment by ZackGoing** [comment]
> you can change subprocess 355 line ,"check=True" to "check=False" , it works for me.

thanks

**Comment by beknazarkydykbekov** [comment]
сук

**Comment by gritYCDA** [comment]
```
subprocess.check_output(["git", "describe"])))
```
=> put in **"--always"**
```
subprocess.check_output(["git", "describe"**, "--always"**])))
```

**Comment by BerilKoksal** [comment]
git init solved my problem
