### ISSUE TITLE
Object bounding box groud-truth of previous frame used in testing as input?

### ISSUE THREAD

**Issue by ChengzhiCU** [xingyizhou/CenterTrack#99]
I tried to understand the code, it seems to me that during testing, the model input a triplet (current image, previous image, heat map generated by groundtruth bounding box of the previous image), and predicts the center of the new object and offset, which does not make sense to me since the ground-truth heat map of the object in the previous frame is not available during testing.

Could the author clarify how the testing is conducted? Does it use the predicted heat map instead of the ground-truth heat map?

**Comment by xingyizhou** [comment]
It takes the predicted tracks, and uses them to render a heatmap as input for the next frame. For the first frame, we just input a zero heatmap. No ground truth is used in testing.

**Comment by ChengzhiCU** [comment]
Thank you very much!
